apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-234620-0e19-service
spec:
  selector:
    app: enterprise-system-234620-0e19
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
